server:
  port: 8081

# https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-endpoints
# actuator 开启所有监控
# management.endpoint.info.enabled=true 开启info监控
# management.endpoint.shutdown.enabled=true 开启shutdown
management:
  endpoints:
    web:
      exposure:
        include:
          "*"

spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/xmicroservice?zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: rootroot
      driver-class-name: com.mysql.jdbc.Driver
         
mybatis:
  config-location: classpath:com/xms/usercenter/mapper/mybatis-config.xml    
#  mapper-locations:
#  - classpath:com/xms/usercenter/mapper/*.xml
  
       