server:
  port: 8081

# https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-endpoints
# actuator 开启所有监控
# management.endpoint.info.enabled=true 开启info监控
# management.endpoint.shutdown.enabled=true 开启shutdown
management:
  endpoints:
    web:
      exposure:
        include:
          "*"

spring:
  datasource:
    druid:
      # 数据库连接信息
      url: jdbc:mysql://127.0.0.1:3306/xmicroservice?zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      #password: rootroot
      password: ENC(KGt5P4Z2OqNG0gTK7wHQPR6vm1KTmr4b)
      driver-class-name: com.mysql.jdbc.Driver
      # 线程池初始化大小, 最小, 最大 , 获取连接等待超时的时间，单位毫秒
      initial-size: 4
      min-idle: 2
      max-active: 8
      max-wait: 60000
      # 用来检测连接是否有效的sql，如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接,单位毫秒;连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall用于防火墙
      filters: stat,wall,slf4j
         
# 指定mybatis-config.xml 和   所有的*Mapper.xml 路径地址，注意不能写成com/xms/usercenter/mapper/*.xml，免得和该路径下的其他xml文件混淆
mybatis:
  config-location: classpath:mybatis-config.xml 
  mapper-locations:
  - classpath:com/xms/usercenter/mapper/**Mapper.xml

# springboot 缺省就会找logback-spring.xml文件，这里直接指定了，path最好指定绝对路径
logging:
  config: classpath:logback-spring.xml
  path: E:/project/eclipse-workspace/xmicroservice/usercenter/logs

# 加密的salt
jasypt:
  encryptor:
    password: 123456

    